# Generated by Django 5.2.7 on 2025-11-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_artist_album_cover_image_song_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist'),
            preserve_default=False,
        ),
    ]
