# Generated by Django 5.2.7 on 2025-11-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='music.genre'),
        ),
    ]
